blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:dish_id>/', views.details, name='details'),
    path('category/<category>/', views.category, name='category'),
    path('country/<country>/', views.country, name='country'),
    path('search/', views.search, name='search'),
    path('category_low_calories/<category>/', views.category_low_calories, name='category_low_calories'),
    path('country_low_calories/<country>/', views.country_low_calories, name='country_low_calories')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone

KINDS_LIST = ['I śniadanie',
            'II śniadanie',
            'obiad',
            'deser',
            'kolacja',
            'przekąska',
            ]

COUNTRIES_LIST = ['Francja',
                'Gruzja',
                'Grecja',
                'Hiszpania',
                'Indie',
                'Tajlandia',
                'INNE',
                ]

UNITS_LIST =['',
            'szt.',
            'ml',
            'l',
            'g',
            'dag',
            'kg',
            ]

KINDS_CHOICES = []
COUNTRIES_CHOICES = []
UNITS_CHOICES = []

for i in range(len(KINDS_LIST)):
    KINDS_CHOICES.append((KINDS_LIST[i], KINDS_LIST[i]))

for i in range(len(COUNTRIES_LIST)):
    COUNTRIES_CHOICES.append((COUNTRIES_LIST[i], COUNTRIES_LIST[i]))

for i in range(len(UNITS_LIST)):
    UNITS_CHOICES.append((UNITS_LIST[i], UNITS_LIST[i]))


class MinMaxFloat(models.FloatField):
    """ FloatField class with limits of values. """
    def __init__(self, min_value=None, max_value=None, *args, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        super(MinMaxFloat, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value' : self.max_value}
        defaults.update(kwargs)
        return super(MinMaxFloat, self).formfield(**defaults)


class Dish(models.Model):
    dish_name = models.CharField(max_length=100)
    recipe = models.TextField()
    dish_image = models.ImageField(blank=True, null=True, upload_to='images/')
    created_date = models.DateTimeField(default=timezone.now)
    kind_of_meal = models.CharField(max_length=30, default=None, choices=KINDS_CHOICES)
    country = models.CharField(max_length=30, default=None, choices=COUNTRIES_CHOICES)
    low_calories = models.BooleanField(default=True)

    def __str__(self):
        return self.dish_name


class Ingredient(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    ingredient = models.CharField(max_length=50)
    quantity = MinMaxFloat(min_value=0.0, blank=True, null=True, default=None)
    unit = models.CharField(max_length=30, blank=True, default=None, choices=UNITS_CHOICES)

    def __str__(self):
        return self.ingredient


class Spice(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    spice = models.CharField(max_length=50)

    def __str__(self):
        return self.spice

blog/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import Dish, KINDS_LIST, COUNTRIES_LIST

def index(request):
    dishes = Dish.objects.order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

def details(request, dish_id):
    dish = Dish.objects.get(pk=dish_id)
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/dish.html', {'dish': dish, 'kinds_list': kinds_list, 'countries_list': countries_list})

def category(request, category):
    dishes = Dish.objects.filter(kind_of_meal=category).order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

def country(request, country):
    dishes = Dish.objects.filter(country=country).order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

def category_low_calories(request, category):
    dishes = Dish.objects.filter(kind_of_meal=category, low_calories=True).order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

def country_low_calories(request, country):
    dishes = Dish.objects.filter(country=country, low_calories=True).order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

def search(request, query=""):
    dishes = Dish.objects
    if request.GET:
        query = request.GET['searchbar']
        searched_words = query.split(' ')
        for word in searched_words:
            dishes = Dish.objects.filter(Q(dish_name__icontains=word)).order_by('-created_date')
    kinds_list = KINDS_LIST
    countries_list = COUNTRIES_LIST
    return render(request, 'blog/index.html', {'dishes': dishes, 'kinds_list': kinds_list, 'countries_list': countries_list})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Cooking blog</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/header.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/navigation.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/container.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/dish.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    </head>
    <body>
        <header class="header">
            <h1 class="header__name">cooking blog</h1>
            <form class="header__search-wrapper" action="{% url 'search' %} "method="get">
                <input class="header__search-bar" type="text" name="searchbar" placeholder="Search...">
                <button class="header__search-button" type="submit"><i class="fa fa-search"></i></button>
            </form>
            <a href="{% url 'admin:index' %}" class="header__login">login</a>
            <a href="{% url 'index' %}" class="header__home">home</a>
        </header>
        <nav class="menu">

            <div class="menu__wrapper">
                <button class="menu__title">KATEGORIE</button>
                <ul class="menu__accordion">
                    {% for kind in kinds_list %}
                    <li><a href="{% url 'category' category=kind %}" class="menu__link">{{ kind }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="menu__wrapper">
                <button class="menu__title">KRAJE</button>
                <ul class="menu__accordion">
                    {% for country in countries_list %}
                    <li><a href="{% url 'country' country=country %}" class="menu__link">{{ country }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="menu__wrapper">
                <button class="menu__title">
                    KATEGORIE <img class="containter__apple-icon" src="/media/images/apple.png" alt="apple icon">
                </button>
                <ul class="menu__accordion">
                    {% for kind in kinds_list %}
                    <li><a href="{% url 'category_low_calories' category=kind %}" class="menu__link">{{ kind }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="menu__wrapper">
                <button class="menu__title">
                    KRAJE <img class="containter__apple-icon" src="/media/images/apple.png" alt="apple icon">
                </button>
                <ul class="menu__accordion">
                    {% for country in countries_list %}
                    <li><a href="{% url 'country_low_calories' country=country %}" class="menu__link">{{ country }}</a></li>
                    {% endfor %}
            </div>
            <script type="text/javascript" src="{% static 'blog/menu.js' %}"></script>
            <div class="menu__legend">
                <img class="containter__apple-icon" src="/media/images/apple.png" alt="apple icon"> - DIETETYCZNE
            </div>
        </nav>
        {% block content %}
        {% endblock %}
 
    </body>
</html>

blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% block content %}

<section class="dish">

    <div class="dish__name">
        <h2>{{ dish.dish_name }}</h2>
    </div>

    <div>
        {% if dish.dish_image %}
        <img class="dish__img" src="{{ dish.dish_image.url }}">
        {% else %}
        <img class="dish__img" src="/media/images/default-dish-img.png">
        {% endif %}
    </div>

    <div class="dish__ingredients">
        <h3>Lista składników:</h3>
        <ul class="dish__ingredients-list">
        {% for ing in dish.ingredient_set.all %}
            {% if ing.quantity == NULL or ing.unit == '' %}
            <li>{{ ing.ingredient }}</li>
            {% else %}
            <li>{{ ing.ingredient }} / {{ ing.quantity|floatformat:"-1" }} {{ ing.unit }}</li>
            {% endif %}
        {% endfor %}
        </ul>
        <h3>Lista przypraw:</h3>
        <ul class="dish__ingredients-list">
        {% for spice in dish.spice_set.all %}
            <li>{{ spice.spice }}</li>
        {% endfor %}
        </ul>
    </div>
      
    <div class="dish__recipe">
        <h3>Przygotowanie:</h3>
        <article class="dish__recipe-details">{{ dish.recipe|linebreaks }}</article>
    </div>

</section>

{% endblock %}

blog/templates/blog/dish.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="container__dish">


    <section class="dish__details">

        <div class="dish__name">
            <h2>{{ dish.dish_name }}</h2>
        </div>

        <div>
            {% if dish.dish_image %}
            <img class="dish__img" src="{{ dish.dish_image.url }}" alt="dish photo">
            {% else %}
            <img class="dish__img" src="/media/images/default-dish-img.png" alt="dish photo">
            {% endif %}
        </div>

        <div class="dish__ingredients">
            <h3>Lista składników:</h3>
            <ul class="dish__ingredients-list">
            {% for ing in dish.ingredient_set.all %}
                {% if ing.quantity == NULL or ing.unit == '' %}
                <li>{{ ing.ingredient }}</li>
                {% else %}
                <li>{{ ing.ingredient }} / {{ ing.quantity|floatformat:"-1" }} {{ ing.unit }}</li>
                {% endif %}
            {% endfor %}
            </ul>
            <h3>Lista przypraw:</h3>
            <ul class="dish__ingredients-list">
            {% for spice in dish.spice_set.all %}
                <li>{{ spice.spice }}</li>
            {% endfor %}
            </ul>
        </div>
        
        <div class="dish__recipe">
            <h3>Przygotowanie:</h3>
            <article class="dish__recipe-details">{{ dish.recipe|linebreaks }}</article>
        </div>

    </section>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

<section class="container">
    {% for dish in dishes %}
    <a href="{% url 'details' dish_id=dish.pk %}" class="container__card">

        {% if dish.dish_image %}
        <img class="container__img" src="{{ dish.dish_image.url }}" alt="dish photo">
        {% else %}
        <img class="container__img" src="/media/images/default-dish-img.png" alt="default photo">
        {% endif %}
        <div class="container__dish-name">
            {% if dish.low_calories == True %} <img class="containter__apple-icon" src="/media/images/apple.png" alt="apple icon"> {% endif %}
            {{ dish }}
        </div>
        <div class="container__dish-wrapper">
            <div class="container__dish-data">
                <img class="container__data-icon" src="/media/images/dish16x16.png" alt="meal icon"> {{ dish.kind_of_meal}}
            </div>
            <div class="container__dish-data">
                <img class="container__data-icon" src="/media/images/world256x256.png" alt="world icon"> {{ dish.country}}
            </div>
            <div class="container__dish-data">
                <img class="container__data-icon" src="/media/images/date512x512.png" alt="date icon"> {{ dish.created_date|date:"Y-m-d" }}
            </div>
        </div>
    </a>
    {% endfor %}
</section>

{% endblock %}